apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  ports:
    - port: 5000
  selector:
    app: flask-app
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fa-pv-claim
  labels:
    app: flask-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flask-app
        tier: frontend
    spec:
      containers:
      - image: flask-app:latest
        name: flask-app
        env:
        - name: FLASK_APP_DB_HOST
          value: flask-app-mongo
        - name: FLASK_APP_DB_PASSWORD
          value: PASSWORDS_IN_PLAIN_TEXT_ARE_BAD_WE_WILL_SHOW_SOMETHING_MORE_SECURE_LATER
        ports:
        - containerPort: 5000
          name: flask-app
        volumeMounts:
        - name: flask-app-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: flask-app-persistent-storage
        persistentVolumeClaim:
          claimName: fa-pv-claim
