{
 "title": "Kubernetes / Horizontal Pod Autoscaler",
 "description": "A quick and simple dashboard for viewing how your horizontal pod autoscaler is doing.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_hpa_metadata_generation{job=\"kube-state-metrics\"}, namespace)"
   },
   {
    "name": "hpa",
    "label": "Name",
    "query": "label_values(kube_hpa_labels{job=\"kube-state-metrics\", namespace=\"$namespace\"}, hpa)"
   },
   {
    "name": "type",
    "query": "label_values(mixin_pod_workload{namespace=~\"$namespace\", workload=~\".+\"}, workload_type)"
   },
   {
    "name": "workload",
    "query": "label_values(mixin_pod_workload{cluster=\"$cluster\", namespace=\"$namespace\"}, workload)"
   },
   {
    "name": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", namespace=\"$namespace\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) mixin_pod_workload{cluster=\"$cluster\", namespace=\"$namespace\", workload=\"$workload\", workload_type=\"$type\"}\n) by (pod)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Desired Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_hpa_status_desired_replicas{job=\"kube-state-metrics\", namespace=\"$namespace\", hpa=\"$hpa\"}"
    }
   ]
  },
  {
   "title": "Current Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_hpa_status_current_replicas{job=\"kube-state-metrics\", namespace=\"$namespace\", hpa=\"$hpa\"}"
    }
   ]
  },
  {
   "title": "Min Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_hpa_spec_min_replicas{job=\"kube-state-metrics\",  namespace=\"$namespace\", hpa=\"$hpa\"}"
    }
   ]
  },
  {
   "title": "Max Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_hpa_spec_max_replicas{job=\"kube-state-metrics\", hpa=\"$hpa\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_hpa_status_desired_replicas{job=\"kube-state-metrics\", hpa=\"$hpa\",namespace=\"$namespace\"}",
     "legendFormat": "Desired"
    },
    {
     "expr": "kube_hpa_status_current_replicas{job=\"kube-state-metrics\", hpa=\"$hpa\",namespace=\"$namespace\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "kube_hpa_spec_max_replicas{job=\"kube-state-metrics\", hpa=\"$hpa\",namespace=\"$namespace\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "kube_hpa_spec_min_replicas{job=\"kube-state-metrics\", hpa=\"$hpa\",namespace=\"$namespace\"}",
     "legendFormat": "Min"
    },
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", namespace=\"$namespace\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) mixin_pod_workload{cluster=\"$cluster\", namespace=\"$namespace\", workload=\"$workload\", workload_type=\"$type\"}\n) * 1.2",
     "legendFormat": "Workload"
    }
   ]
  }
 ]
}