apiVersion: v1
kind: Service
metadata:
  name: fa-service
  labels:
    app: flask-app
spec:
  selector:
    app: flask-app
    tier: frontend
  ports:
  - name: flask-app
    protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fa-service
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: flask-app
  endpoints:
  - port: flask-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
      tier: frontend
  replicas: 4
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flask-app
        tier: frontend
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: flask-app
          image: deepnadig/ergo:1.3
          imagePullPolicy: Always
          ports:
            - name: flask-app
              containerPort: 5000
