apiVersion: v1
kind: Service
metadata:
  name: mongo-flask-app
  labels:
    app: flask-app
spec:
  ports:
    - port: 27017
  selector:
    app: flask-app
    tier: mongo
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
  labels:
    app: flask-app
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-flask-app
  labels:
    app: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
      tier: mongo
  replicas: 1
  serviceName: mongo-flask-app
  template:
    metadata:
      labels:
        app: flask-app
        tier: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: mongo:4
        name: mongo
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
        command:
          - mongod
          - "--bind_ip"
          - 0.0.0.0
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim
